### ISSUE TITLE
在 `meow_emoji.dict.yaml` 新添加的颜文字不会生效

### ISSUE THREAD

**Issue by acgtyrant** [hitigon/meow-emoji-rime#5]
不停地重新部署，新添加的颜文字也不会匹配出来，困惑极了！

**Comment by hitigon** [comment]
测试过没什么问题，请检查一下新添加的格式是不是有问题(°ー°〃=)>

**Comment by acgtyrant** [comment]
原来之间的空白要用 Tab 制表符啊……而且 Vim 自动转 Tab 为空格的功能让我绕圈子了半天。
